<a href="https://colab.research.google.com/github/mpagesbat/03MAIR---Algoritmos-de-Optimizacion---2019/blob/master/AG2/Marc_Pages_AG2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

nombre: Marc Pagès <br>
Link:https://colab.research.google.com/drive/1pTkP9wIwSqJJ9iL9t3UI8Ol3bFu_d6BB
<br>Actividad Guiada 2

**que complejidad tiene el algoritmo por fuerza bruta?**  Coste computacional n! <br>
**a partir de que dimension el algoritmo por fuerza bruta deja de ser una opción?**<br>
hemos medido el tiempo de ejecución con varias matrices de valores:<br>
-dimension= 5  tiempo ejecución=0,028seg<br>
-dimension= 6  tiempo ejecución=0,3616seg<br>
-dimension= 7  tiempo ejecución=0,2,686seg<br>
-dimension= 8  tiempo ejecución=26,03seg<br>
-dimension= 9  tiempo ejecución=243,34seg<br>
a partir de estas dimensiones, el algoritmo ya empieza a no ser bueno.


**a partir de que dimension el algoritmo por ramificacion y poda deja de ser una opción?**<br>
hemos medido el tiempo de ejecución con varias matrices de valores:<br>
-dimension= 9  tiempo ejecución=0,08343seg<br>
-dimension= 14  tiempo ejecución=4,92seg<br>
-dimension= 15  tiempo ejecución=16,36seg<br>
-dimension= 16  tiempo ejecución=26,03seg<br>
a partir de estas dimensiones, el algoritmo ya empieza a no ser bueno.


**PROBLEMA VIAJE POR EL RIO**

In [0]:
TARIFAS = [
[0,5,4,3,999,999,999],  #desde nodo 0
[999,0,999,2,3,999,11],  #desde nodo 1
[999,999, 0,1,999,4,10], #desde nodo 2
[999,999,999, 0,5,6,9],
[999,999, 999,999,0,999,4],
[999,999, 999,999,999,0,3],
[999,999,999,999,999,999,0]
]
def Precios(TARIFAS):
################################################################  
  #Total de Nodos
  N = len(TARIFAS[0])
  
  #Inicialización de la tabla de precios
  PRECIOS = [ [9999]*N for i in [9999]*N]
  RUTA = [ [""]*N for i in [""]*N]
  
  for i in range(N-1):
    for j in range(i+1, N):  
      MIN = TARIFAS[i][j] #calculo coste i,j minimo
      RUTA[i][j] = i  #guardo que nodo es
      
      for k in range(i, j):  #busco un nodo intermedio k que permita ir de i a j con menor coste
        if PRECIOS[i][k] + TARIFAS[k][j] < MIN:
            MIN = min(MIN, PRECIOS[i][k] + TARIFAS[k][j] )
            RUTA[i][j] = k
        PRECIOS[i][j] = MIN
        
  return PRECIOS,RUTA


In [0]:
PRECIOS,RUTA = Precios(TARIFAS)  
#print(PRECIOS[0][6])

print("PRECIOS")
for i in range(len(TARIFAS)):
  print(PRECIOS[i])

print("\nRUTA")  
for i in range(len(TARIFAS)):
  print(RUTA[i]) 
  # la matriz ruta: ['', 0, 0, 0, 1, 2, 5]  de ir de 0 a 0 =>no existe  de ir de 0 a 1=>pasa por el 0, de ir de 0 a 2 => pasa por el 1, ir de 0 a 5 => pasa por el 2...

PRECIOS
[9999, 5, 4, 3, 8, 8, 11]
[9999, 9999, 999, 2, 3, 8, 7]
[9999, 9999, 9999, 1, 6, 4, 7]
[9999, 9999, 9999, 9999, 5, 6, 9]
[9999, 9999, 9999, 9999, 9999, 999, 4]
[9999, 9999, 9999, 9999, 9999, 9999, 3]
[9999, 9999, 9999, 9999, 9999, 9999, 9999]

RUTA
['', 0, 0, 0, 1, 2, 5]
['', '', 1, 1, 1, 3, 4]
['', '', '', 2, 3, 2, 5]
['', '', '', '', 3, 3, 3]
['', '', '', '', '', 4, 4]
['', '', '', '', '', '', 5]
['', '', '', '', '', '', '']


In [0]:
def calcular_ruta(RUTA, desde, hasta):   #aplicamos recursividad
  if desde == hasta:
    #print("Ir a :" + str(desde))
    return desde 
  else:
    return str(calcular_ruta(RUTA, desde, RUTA[desde][hasta])) +  ',' + str(RUTA[desde][hasta]) 

print("\nLa ruta es:")  
calcular_ruta(RUTA, 0,6) #para ir de 0 a 6   (que vaya a 0(el 0 sale repetido) despues a 2 y despues a 5)


La ruta es:


'0,0,2,5'

**algoritmo ramificacion y poda: problema de asignación de agentes**


In [1]:
import random
import numpy as np
from time import time

COSTES = []
n=4

COSTES = np.random.randint(0, 100, size=(n, n))
print(COSTES)

#COSTES=[[11,12,18,40],
#        [14,15,13,22],
#        [11,17,19,23],
#        [17,14,20,28]]    #filas=agentes columnas=tareas


def valor(S,COSTES):
  VALOR = 0
  for i in range(len(S)):
    VALOR += COSTES[S[i]][i] 
  return VALOR
  
valor((0, 1, 2, 3),COSTES)

[[42 22 68 39]
 [89 63 16 51]
 [58 84 21 11]
 [75 45 88 85]]


211

In [2]:

from time import time
import itertools
tiempo_inicial = time() 
#por fuerza bruta
#coste computacional factorial n!
def fuerza_bruta(COSTES):
  mejor_valor=10e10
  mejor_solucion=()
  for s in list(itertools.permutations(range(len(COSTES)))):
    valor_tmp=valor(s,COSTES)
    if valor_tmp<mejor_valor:
      mejor_valor=valor_tmp
      mejor_solucion=s
    print("la mejor solucion es:",mejor_solucion,"con valor:",mejor_valor)
fuerza_bruta(COSTES)
tiempo_final = time() 
 
tiempo_ejecucion = tiempo_final - tiempo_inicial
print(tiempo_ejecucion)

la mejor solucion es: (0, 1, 2, 3) con valor: 211
la mejor solucion es: (0, 1, 3, 2) con valor: 204
la mejor solucion es: (0, 1, 3, 2) con valor: 204
la mejor solucion es: (0, 1, 3, 2) con valor: 204
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114
la mejor solucion es: (0, 3, 1, 2) con valor: 114


In [0]:
#Coste inferior para soluciones parciales
#  (1,3,) Se asigna la tarea 1 al agente 0 y la tarea 3 al agente 1

def CI(S,COSTES):
  VALOR = 0
  #Valores establecidos
  for i in range(len(S)):
    VALOR += COSTES[i][S[i]]

  #Estimacion
  for i in range(  len(COSTES)):
    if i not in S:
      VALOR += min( [ COSTES[j][i] for j in range(len(S), len(COSTES))  ])
  return VALOR

In [0]:
#Genera tantos hijos como como posibilidades haya para la siguiente elemento de la tupla
#(0,) -> (0,1), (0,2), (0,3)
def crear_hijos(NODO, N):
  HIJOS = []
  for i in range(N):
    if i not in NODO:
      HIJOS.append({'s':NODO +(i,)    })
  return HIJOS

In [0]:
def CS(S,COSTES):     #cota superior
  VALOR = 0
  #Valores establecidos
  for i in range(len(S)):
    VALOR += COSTES[i][S[i]]

  #Estimacion
  for i in range(  len(COSTES)):
    if i not in S:
      VALOR += max( [ COSTES[j][i] for j in range(len(S), len(COSTES))  ])
  return VALOR

In [6]:
def ramificacion_y_poda(COSTES):
#Construccion iterativa de soluciones(arbol). En cada etapa asignamos un agente(ramas).
#Nodos del grafo  { s:(1,2),CI:3,CS:5  }
  #print(COSTES)
  DIMENSION = len(COSTES)  
  MEJOR_SOLUCION=tuple( i for i in range(len(COSTES)) )
  CotaSup = valor(MEJOR_SOLUCION,COSTES)
  #print("Cota Superior:", CotaSup)

  NODOS=[]
  NODOS.append({'s':(), 'ci':CI((),COSTES)    } )

  iteracion = 0

  while( len(NODOS) > 0): #mientras tenga nodos en mi lista
    iteracion +=1

    nodo_prometedor = [ min(NODOS, key=lambda x:x['ci']) ][0]['s']  #buscamos el nodo mas prometedor(estamos minimizando): la mejor cota inferior
    #print("Nodo prometedor:", nodo_prometedor)

    #Ramificacion
    #Se generan los hijos
    HIJOS =[ {'s':x['s'], 'ci':CI(x['s'], COSTES)   } for x in crear_hijos(nodo_prometedor, DIMENSION) ]#creamos los hijos

    #Revisamos la cota superior y nos quedamos con la mejor solucion si llegamos a una solucion final
    NODO_FINAL = [x for x in HIJOS if len(x['s']) == DIMENSION  ]
    if len(NODO_FINAL ) >0: 
      #print("\n********Soluciones:",  [x for x in HIJOS if len(x['s']) == DIMENSION  ] )
      if NODO_FINAL[0]['ci'] < CotaSup:
        CotaSup = NODO_FINAL[0]['ci']
        MEJOR_SOLUCION = NODO_FINAL
 
    #Poda
    HIJOS = [x for x in HIJOS if x['ci'] < CotaSup   ] #podamos todos los hijos con cota mas grande que la superiror

    #Añadimos los hijos 
    NODOS.extend(HIJOS) 

    #Eliminamos el nodo ramificado
    NODOS =  [  x for x in NODOS if x['s'] != nodo_prometedor    ]
   
    print("La solucion final es:" ,MEJOR_SOLUCION , " en " , iteracion , " iteraciones" , " para dimension: " ,DIMENSION  )
tiempo_inicial = time()       
ramificacion_y_poda(COSTES)
tiempo_final = time() 
 
tiempo_ejecucion = tiempo_final - tiempo_inicial
print(tiempo_ejecucion)

La solucion final es: (0, 1, 2, 3)  en  1  iteraciones  para dimension:  4
La solucion final es: (0, 1, 2, 3)  en  2  iteraciones  para dimension:  4
La solucion final es: (0, 1, 2, 3)  en  3  iteraciones  para dimension:  4
La solucion final es: (0, 1, 2, 3)  en  4  iteraciones  para dimension:  4
La solucion final es: (0, 1, 2, 3)  en  5  iteraciones  para dimension:  4
La solucion final es: [{'s': (0, 2, 3, 1), 'ci': 114}]  en  6  iteraciones  para dimension:  4
La solucion final es: [{'s': (0, 2, 3, 1), 'ci': 114}]  en  7  iteraciones  para dimension:  4
La solucion final es: [{'s': (0, 2, 3, 1), 'ci': 114}]  en  8  iteraciones  para dimension:  4
La solucion final es: [{'s': (0, 2, 3, 1), 'ci': 114}]  en  9  iteraciones  para dimension:  4
La solucion final es: [{'s': (0, 2, 3, 1), 'ci': 114}]  en  10  iteraciones  para dimension:  4
La solucion final es: [{'s': (0, 2, 3, 1), 'ci': 114}]  en  11  iteraciones  para dimension:  4
La solucion final es: [{'s': (0, 2, 3, 1), 'ci': 114}